### ISSUE TITLE
Missing angular.json files

### ISSUE THREAD

**Issue by mikelhamer** [DeborahK/Angular-Routing#10]
The projects in this repo don't seem to have the generated angular.json files required for some IDEs to recognize the app as an Angular application. Checking out your other repos work fine, but this one isn't being recognized as an Angular app.

**Comment by DeborahK** [comment]
This code was created for Angular v2, *before* the Angular CLI came out. So it does not have the files that the Angular CLI uses/needs. 

The course associated with this code is being updated to Angular v7 as we speak. So this code will be replaced with Angular v7 code (using the Angular CLI) in about 2 weeks.

**Comment by mikelhamer** [comment]
Oh! That makes sense. Thanks for the quick reply, love your courses!
