### ISSUE TITLE
Add Route Animations to enhance User Experience

### ISSUE THREAD

**Issue by HansS** [DeborahK/Angular-Routing#11]
Here is some samples from angularfirebase.com:
https://www.youtube.com/watch?v=7JA90VI9fAI&feature=youtu.be

**Comment by DeborahK** [comment]
Thank you for sharing the link. I have a section on Route Animations in the course currently. They are not as fancy as the ones shown in the video, but provide the basics. 

I'm closing this. Let me know if I misunderstand your issue.
