### ISSUE TITLE
enableTracing based on a config value

### ISSUE THREAD

**Issue by wwrafter** [DeborahK/Angular-Routing#2]
Is there a way to enable route tracing based on a config value? I'm thinking more in terms of troubleshooting in a production environment where I really can't rebuild the app.

**Comment by DeborahK** [comment]
Not that I know of. Someone asked this same question several months ago on stackoverflow and never received an answer.

http://stackoverflow.com/questions/41645399/how-to-enable-route-tracing-programatically-in-angular-2

**Comment by wwrafter** [comment]
Yeah, that was my question :-)

**Comment by wwrafter** [comment]
I did some more research, and updated the stackoverflow question. Doesn't look doable without a change to the router (which I detailed in the update).
