### ISSUE TITLE
Not working with Node Latest Stable version

### ISSUE THREAD

**Issue by jagdeepjeetsingh26** [DeborahK/Angular-Routing#22]
Please update the code to Angular 10 -14

**Comment by DeborahK** [comment]
When you say "not working" what is it doing?

Earlier this week, I downloaded the code, ran `npm install` and `npm start` and it worked fine. It dumped a bunch of warnings, but completed successfully.

I'm running node v16.15.1

(Pluralsight is currently planning on doing a full update to the Angular catalog for Angular v15.)

**Comment by jagdeepjeetsingh26** [comment]
Its not working with node 16.17, but i am able to update the package config
file to 14 ..and its working fine

Thanks
Jagdeep singh

**Comment by DeborahK** [comment]
FYI - I've added v14 code to this repository.

**Comment by jagdeepjeetsingh26** [comment]
Awesome, thanks!
