### ISSUE TITLE
Why isv

### ISSUE THREAD

**Issue by rudvfaden** [DeborahK/Angular-Routing#23]
Why is there 2 folder with the same name?
<img width="203" alt="Skærmbillede 2022-09-09 kl  19 41 24" src="https://user-images.githubusercontent.com/2445577/189412075-9d33d8ef-3234-49eb-983b-e53497ba2880.png">

**Comment by DeborahK** [comment]
The read-me should explain (just scroll down on the main page for this repo if you don't see it).

If you want to work with code that *exactly* matches the course, use the APM-Start and APM-Final folders. But they are Angular v10. Angular is now on v14. So I provided a version of the Start and Final folders updated to Angular v14 for your reference.

The two key changes:
- Angular is now strongly typed. So every variable needs to be initialized and appropriately typed.
- Bootstrap 5 is a bit different from Bootstrap 4.

Does that answer your question?

**Comment by rudvfaden** [comment]
Yes. Thank you

fre. 9. sep. 2022 19.47 skrev Deborah Kurata ***@***.***>:
