### ISSUE TITLE
Going "back"

### ISSUE THREAD

**Issue by wwrafter** [DeborahK/Angular-Routing#3]
Is there a way to go "back"? From the Edit page, I'd like to go back to the caller, which is either 'products' or 'products/:id'.

**Comment by DeborahK** [comment]
You could use a technique similar to the one shown in the course: https://github.com/DeborahK/Angular-Routing/blob/master/APM-Final/src/app/user/auth-guard.service.ts

Or you could use query parameters as shown here: http://stackoverflow.com/a/42778150/1647604

Alternatively, you could check out the blog post here: http://stackoverflow.com/questions/35279291/angular2-how-to-find-out-what-was-previous-page-url-when-using-angular2-routing

**Comment by DeborahK** [comment]
Did one of those answer your question? If so, can you close this issue? 

Thanks!

**Comment by wwrafter** [comment]
I had to put down the project for a bit, so I haven't been able to test things out. But feel free to close the issue.

**Comment by DeborahK** [comment]
Reopen later as needed.

Thanks!
