### ISSUE TITLE
APM-Start-CLI available

### ISSUE THREAD

**Issue by fmorriso** [DeborahK/Angular-Routing#6]
I have taken your APM-Start and converted it to Angular-CLI 1.0.0 and Angular 4.0.3 and published to a public GitHub at:
[APM-Start-CLI](https://github.com/fmorriso/APM-Start-CLI)

Once I complete your Angular Routing Course, I'll try to publish my edition as APM-Routed (currently private since I am only starting Module 3 of your course).

**Comment by DeborahK** [comment]
Thank you for post! 

Since this is not really an issue with my existing code, I'm closing it. But I'll keep your comments here for others to find if they are looking for a CLI version of the code.
