### ISSUE TITLE
Refresh issue with Child Route 

### ISSUE THREAD

**Issue by shaheer-scania** [DeborahK/Angular-Routing#8]
Hello Deborah,

I have facing an issue with Child routing. Could you please support me to find a fix.

I am using child route in my application. When I do direct refresh on child path, the style.css is getting loaded on parent path instead of root. This is causing the page to loose global styling as style.css is not found on root. Its working perfectly when navigating with angular routing, but issue happens only I do browser refresh on child route.

The above issue is not reproducible in local, but happening only when I deploy angular application in AWS cloud-front. I have tried all possible fixes like setting base href, etc.. but no luck

Please let me know if you have any pointer to fix this issue

Regards

Shaheer

**Comment by DeborahK** [comment]
Your best bet for these types of issues is to post to stackoverflow. The experts there should be able to help you.
